Repository NHSDigital/bcss-playwright, pull requests merged in 2025-05, with the labels that each got.

#43 BCSS-20351: Test Runner POC Amendments
  .github/actions/run-playwright-tests/action.yml
  .github/workflows/execute-tests.yaml
Labels: enhancement

#41 Refactoring Batch Processing to allow obtaining subjects from PDF Files
  requirements.txt
  tests/smokescreen/test_compartment_1.py
  utils/batch_processing.py
  utils/pdf_reader.py
Labels: enhancement

#42 https://nhsd-jira.digital.nhs.uk/browse/BCSS-20365 - BCSS - Playwrig…
  pages/datasets/colonoscopy_dataset_page.py
  pages/screening_subject_search/contact_with_patient_page.py
  tests/smokescreen/test_compartment_5.py
Labels: enhancement

#48 Feature/bcss 20436 calendar picker util markdown doc and docstrings
  docs/utility-guides/CalendarPicker.md
  tests/smokescreen/test_compartment_4.py
  utils/calendar_picker.py
Labels: documentation

#46 Feature/bcss 20327 compartment 5 utils
  docs/utility-guides/BatchProcessing.md
  docs/utility-guides/PDFReader.md
  pages/communication_production/batch_list_page.py
  pages/screening_practitioner_appointments/screening_practitioner_day_view_page.py
  pages/screening_subject_search/advance_fobt_screening_episode_page.py
  pages/screening_subject_search/subject_screening_search_page.py
  pages/screening_subject_search/subject_screening_summary_page.py
  tests/smokescreen/bcss_smokescreen_tests.properties
  tests/smokescreen/test_compartment_2.py
  tests/smokescreen/test_compartment_3.py
  tests/smokescreen/test_compartment_5.py
  tests/test_calendar_picker_methods.py
  tests_utils/test_calendar_picker_util.py
  utils/batch_processing.py
  utils/oracle/oracle_specific_functions.py
  utils/pdf_reader.py
Labels: documentation, enhancement

#50 BCSS-20460: Rebase with playwright-python-blueprint
  .gitignore
  .vscode/extensions.json
  README.md
  conftest.py
  requirements.txt
  setup_env_file.py
  utils/axe.py
  utils/user_tools.py
Labels: enhancement, dependencies

#49 Adding Oracle markdown doc and docstrings and fixing spelling
  docs/utility-guides/Oracle.md
  tests/smokescreen/bcss_smokescreen_tests.properties
  utils/oracle/oracle.py
  utils/oracle/oracle_specific_functions.py
Labels: documentation

#52 Moving generic pytest fixtures to conftest
  conftest.py
  setup_env_file.py
  tests/smokescreen/test_compartment_1.py
  tests/smokescreen/test_compartment_2.py
  tests/smokescreen/test_compartment_3.py
  tests/smokescreen/test_compartment_4.py
  tests/smokescreen/test_compartment_5.py
  tests/test_call_and_recall_page.py
  tests/test_fit_test_kits_page.py
  tests/test_organisations_page.py
  tests/test_reports_page.py
  tests/test_screening_subject_search_page.py
  utils/user_tools.py
Labels: enhancement

#53 Adding markdown document and docstrings for Load Properties Util
  docs/utility-guides/LoadProperties.md
  utils/load_properties_file.py
Labels: documentation

#51 Feature/bcss 20441 tableutil markdown doc and doc strings
  docs/utility-guides/TableUtil.md
  utils/table_util.py
Labels: documentation

#55 Added logic to check and correct for duplicate records.
  utils/oracle/oracle.py
  utils/oracle/oracle_specific_functions.py
Labels: documentation, enhancement

#56 Compartment 6 codegen code
  tests/smokescreen/test_compartment_6.py
Labels: enhancement

#57 Feature/bcss 20438 fit kit logged docstrings and md
  docs/utility-guides/FitKitLogged.md
  utils/fit_kit_logged.py
Labels: documentation

#61 Fixing the calendar util to select the correct day.
  tests/test_calendar_picker_methods.py
  utils/calendar_picker.py
Labels: enhancement

#60 Feature/bcss 20479 compartment 6 pom investigation dataset page
  pages/datasets/investigation_dataset_page.py
  tests/smokescreen/test_compartment_6.py
Labels: enhancement

#62 Bathc Processing Util Rework
  docs/utility-guides/BatchProcessing.md
  pages/screening_subject_search/subject_screening_summary_page.py
  utils/batch_processing.py
  utils/screening_subject_page_searcher.py
Labels: enhancement

#63 Feature/bcss 20443 compartment 6 pom record diagnosis date
  pages/screening_subject_search/record_diagnosis_date_page.py
  pages/screening_subject_search/subject_screening_summary_page.py
  tests/smokescreen/test_compartment_6.py
  utils/batch_processing.py
Labels: enhancement

#59 Feature/bcss 20476 c6 pom advance fobt screening episode
  pages/screening_subject_search/advance_fobt_screening_episode_page.py
  tests/smokescreen/test_compartment_6.py
Labels: enhancement

#64 Feature/bcss 20440 playwright utils markdown screening subject page searcher
  docs/utility-guides/ScreeningSubjectPageSearcher.md
  utils/screening_subject_page_searcher.py
Labels: documentation

#65 Feature/bcss 20478 c6 pom handover into symptomatic care page
  pages/screening_subject_search/handover_into_symptomatic_care_page.py
  tests/smokescreen/test_compartment_6.py
Labels: enhancement

#66 Fixed failing test
  tests/smokescreen/test_compartment_5.py
Labels: enhancement

#67 Feature/bcss 20477 c6 pom diagnostic test outcome page
  pages/screening_subject_search/diagnostic_test_outcome_page.py
  tests/smokescreen/test_compartment_6.py
Labels: enhancement

#68 Docstring is newly added for POM - ContactWithPatientPage.
  pages/screening_subject_search/contact_with_patient_page.py
Labels: documentation

#69 Subject Demographic Util
  docs/utility-guides/SubjectDemographics.md
  pages/screening_subject_search/subject_demographic_page.py
  requirements.txt
  utils/subject_demographics.py
Labels: documentation, enhancement

#70 Feature/bcss 20537 c6 pom subject datasets page
  pages/datasets/subject_datasets_page.py
  tests/smokescreen/test_compartment_6.py
Labels: enhancement

#71 Feature/bcss 20517 dynamic css locators
  docs/utility-guides/DatasetField.md
  pages/datasets/investigation_dataset_page.py
  tests/smokescreen/test_compartment_6.py
  utils/dataset_field_util.py
Labels: documentation, enhancement

#73 Fixed all pytest warnings at the end of a test run
  pages/datasets/investigation_dataset_page.py
  pytest.ini
Labels: enhancement

#75 Feature/bcss 20521 c6 investigation dataset navigation util
  docs/utility-guides/InvestigationDataset.md
  pages/datasets/investigation_dataset_page.py
  tests/smokescreen/test_compartment_6.py
  utils/investigation_dataset.py
Labels: documentation, enhancement

#78 Feature/bcss 20550 c6 logging
  tests/smokescreen/test_compartment_6.py
Labels: enhancement

#80 Feature/bcss 20633 subject demographics util updates
  docs/utility-guides/SubjectDemographics.md
  tests/smokescreen/test_compartment_6.py
  utils/subject_demographics.py
Labels: documentation, enhancement

#81 Feature/bcss 20632 screening subject page searcher markdown updates
  docs/utility-guides/ScreeningSubjectPageSearcher.md
Labels: documentation

#88 Feature/bcss 20625 datetimeutils markdown updates
  docs/utility-guides/DateTimeUtility.md
Labels: documentation

#87 Feature/bcss 20624 calendar picker markdown updates
  docs/utility-guides/CalendarPicker.md
Labels: documentation

#90 Addressing feedback comments from reviews
  docs/utility-guides/UserTools.md
Labels: documentation

#89 BCSS – Playwright - Load Properties Markdown Improvements
  docs/utility-guides/LoadProperties.md
Labels: documentation
